### ISSUE TITLE
Updating the angular version?

### ISSUE THREAD

**Issue by rlweb** [wilk/ng-websocket#22]
Bower keeps asking me which version to use of angular because the version in the bower file is lower than my current version of angular. Could I post a PR?

**Comment by maroshii** [comment]
@rlweb did you encounter any issues with this using angular >=1.4?

**Comment by redi-madhava** [comment]
I tried using v1.4.3 or angular and put a resolutions in bower.json for angular 1.4.3 or ~1.4.3. I keep getting the error due to angular version conflict (as ng-websocket specifies v1.3.2 and I don't have that version of angular in intranet artifactory):

Additional error details:
No version found for ~1.3.2. Available tags: [1.4.7, 1.4.3, 1.4.5], Available branches: []

**Comment by wilk** [comment]
This project is no longer mainteined. Sorry.
